project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "*.md"
    - "!etc/"
  resources:
    - "Resources/**"

website:
  title: "Andrew Allyn"
  search: false
  navbar:
    right:
      - text: Welcome
        href: index.qmd
      - text: Research
        href: research/Research.qmd
      - text: Ramblings
        href: ramblings/Ramblings.qmd
      - text: Resume
        href: resume/Resume.qmd
      - icon: github
        href: https://github.com/aallyn
      - icon: envelope-at-fill
        href: mailto:andrew.allyn@gmail.com

format:
  html:
    theme: simplex
    css: styles.css
    toc: true



