project:
  type: website
  output-dir: docs

website:
  title: "Andrew Allyn"
  search: false
  navbar:
    right:
      - href: index.qmd
        text: Welcome
      - Research.qmd
      - Resume.qmd
      - Ramblings.qmd
      - icon: github
        href: https://github.com/aallyn
      - icon: envelope-at-fill
        href: mailto:andrew.allyn@gmail.com

format:
  html:
    theme: simplex
    css: styles.css
    toc: true
  # pdf:
  #   author: Andrew Allyn
  #   pdf-engine: weasyprint



