project:
  type: website
  output-dir: docs

website:
  title: "Andrew Allyn"
  navbar:
    left:
      - href: index.qmd
        text: Welcome
      - about.qmd
      - Resume.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



