project:
  type: website
  output-dir: docs

freeze: true

website:
  title: "Andrew Allyn"
  search: false
  navbar:
    right:
      - text: "Welcome"
        href: index.qmd
      - text: "Research"
        href: research/index.qmd
      - text: "Ramblings"
        href: ramblings/index.qmd
      - text: "Resume"
        href: resume/index.qmd
      - icon: github
        href: https://github.com/aallyn
      - icon: envelope-at-fill
        href: mailto:andrew.allyn@gmail.com

format:
  html:
    theme: simplex
    css: styles.css
    toc: true



