---
title: Resume
name: Andrew Allyn
position: "Senior Research Manager"
address: "Gulf of Maine Research Institute"
phone: 
www: aallyn.github.io
email: andrew.allyn@gmail.com
github: aallyn
aboutme: ""
date: "`r format(Sys.time(), '%B %Y')`"
headcolor: "000000"
output: vitae::awesomecv
---

::: {.print-only .contact-block}
andrew.allyn@gmail.com
:::

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
library(here)
library(vroom)
library(dplyr)
library(lubridate)
library(glue)
library(scholar)
library(rorcid)

myorcid <- "0000-0002-1584-0198"
```

# Education

```{r}
tribble(
  ~ Degree, ~ Year, ~ Institution, ~ Where,
  "PhD Marine Science and Technology", "February 2012 - February 2024", "University of Massachusetts Amherst", "Amherst, MA",
  "MS Wildlife and Fisheries Conservation", "September 2008 - February 2012", "University of Massachusetts Amherst", "Amherst, MA",
  "BA English", "September 2003 - May 2007", "Connecticut College", "New London, CT"
) %>% 
  detailed_entries(Degree, Year, Institution, Where)
```

# Publications

```{r}
all_pubs<- scholar::get_publications("-dn-gUsAAAAJ") %>% 
  detailed_entries(
    what = title,
    when = year,
    with = author,
    where = journal,
    why = cites
  )
```

<!-- 
# Positions

```{r}
jobs <- vroom(here::here("data", "jobs.csv"))

jobs |>
  arrange(desc(dates)) |> 
  detailed_entries(
    what = glue("{role} - {company}"),
    when = dates
)
```


# Qualifications

```{r}
edu <- vroom(here("data", "education.csv"))

detailed_entries(edu,
                 when = glue("{start_date}--{end_date}"),
                 what = glue("{degree} - {uni}"))

```

# Skills

```{r}
skills <- vroom(here::here("data", "skills.csv")) |>
  group_by(category) |>
  mutate(skill = paste(skill, collapse = ", ")) |>
  ungroup() |>
  unique()

skills |>
  detailed_entries(what = skill, with = category)
```

# Selected publications

```{r}
pubs <- vroom(here::here("data", "publications.csv"), delim = "\t")

pubs |>
  detailed_entries(
    what = publication
)
```

*See [here](https://scholar.google.com/citations?user=GqZm90IAAAAJ&hl=en) for a full list of my publications.*

# Selected software

```{r}
software <- vroom(here::here("data", "software.csv")) |>
  arrange(desc(when))

software |>
  detailed_entries(
    what = glue("{package} - {what}"), when = where
)
```

*Software that I have primarily developed has had over 30k downloads and been used/is used in multiple public health organisations such as the WHO and the ECDC. Software that I have managed the development of has had over 20k downloads. See [my GitHub](https://github.com/seabbs/) for more on my software output.*

# Research (Co-) Supervision

```{r research}
supervision <- vroom(here::here("data", "supervision.csv"))

supervision |>
  detailed_entries(
    what = glue("{who} - {what}"),
    when = when
)
```
# Teaching

```{r}
teaching <- vroom(here::here("data", "teaching.csv")) |>
  arrange(desc(when))

teaching |>
  detailed_entries(
    what = what, when = when
)
```


# Selected presentations

```{r}
presentations <- vroom(here::here("data", "presentations.csv")) |>
  arrange(desc(when))

presentations |>
  detailed_entries(
    what = with, when = when
)
```

*See the details, slides, and recordings of all my presentations [here](test)*

# Service

```{r}
service <- vroom(here::here("data", "service.csv"))

service |>
  detailed_entries(what = glue("{type} - {details}"), when = when)
``` -->