---
title: "Research"
---

My mission is to support sustainable and equitable marine ecosystem management through advanced spatial ecology and prediction science. I develop and apply cutting-edge quantitative approaches to understand and predict spatial relationships in marine ecosystems across temporal scales. My research provides insights into how species distributions and predator-prey dynamics respond to environmental changes. I am particularly interested in how spatial and temporal scales impact our capacity to understand and predict ecological patterns. Throughout my work, I strive to generate actionable knowledge that stakeholders can immediately apply to marine spatial planning, sustainable resource management, and climate adaptation efforts.

To accomplish this mission, I work across four research themes:

1.  [**Climate biogeography**](#climate-biogeography): Mapping the redistribution of species and ecological communities under potential climate conditions to support adaptation planning efforts.  
2.  [**Ecological forecasting**](#ecological-forecasting): Validating existing frameworks and developing novel approaches to generate near-term predictions that inform management and conservation decisions at seasonal to decadal time scales.  
3.  [**Predator-prey dynamics**](#predator-prey-dynamics): Applying and enhancing joint species distribution models to understand how species-specific responses to ecosystem changes alter spatial and temporal relationships among predators and prey.
4. [**Marine spatial planning and resource management**](#marine-spatial-planning-and-resource-management): Integrating model outputs into spatial planning and resource management to balance ecological and economic priorities in the ocean.

## Climate Biogeography
### Overview
As ocean temperatures rise, one of the clearest biological responses has been the redistribution of marine species. Across the globe, species are shifting their ranges — often toward cooler waters or deeper depths — in search of more suitable environmental conditions. These distribution changes can cascade through ecosystems, altering community structure and predator–prey dynamics, changing habitat use, and affecting the availability of key resources. For communities and decision-makers, this creates new challenges around resource access, governance, and equity. Climate biogeography is the field focused on understanding, quantifying, and projecting these shifts. By examining how species distributions respond to environmental change, climate biogeography provides essential insights for long-term planning and adaptation — from conserving biodiversity to managing fisheries and sustaining coastal livelihoods.

To anticipate and respond to these changes, we develop and apply advanced spatio-temporal models that characterize species–environment relationships and account for latent spatial and temporal structure (e.g., through tools like sdmTMB and tinyVAST). These statistical models are then coupled with global climate projections to forecast future distributional shifts across scales — from entire large marine ecosystems to specific fisheries and communities. Incorporating spatial patterns of fishing effort allows us to link ecological projections with real-world impacts, supporting more informed and adaptive management in a changing ocean.

### Current Projects
[**Crossing Boundaries: Understanding and Projecting Species Distribution Shifts in U. S. and Canadian Waters**](https://gmri.org/projects/crossing-boundaries-understanding-and-projecting-species-distribution-shifts-u-s-and-canadian-waters/). 

### Relevant Publications
- Allyn et al. *In prep.* Intuition and considerations for projecting mixed effects species distribution models under future climate conditions.
- Ferguson et al. *In prep.* Shifts and expansion in a spatially structured fish stock spanning international borders in the Northwest Atlantic.
- Braun et al., 2023. Widespread habitat loss and redistribution of marine top predators in a changing ocean. [*Science Advances.*](https://www.science.org/doi/full/10.1126/sciadv.adi2718)
- Allyn et al. 2020. Comparing and synthesizing quantitative distribution models and qualitative vulnerability assessments to project marine species distributions under climate change. [*PLOS One.*](https://doi.org/10.1371/journal.pone.0231595)

### Code
- Single Species SDMs: *Coming soon* A {targets} worfklow to readily fit, validate and project mixed effects models fitted with the sdmTMB modeling approach. Under active development.
- [Targets SDM](https://github.com/aallyn/TargetsSDM): A {targets} workflow designed to readily fit, validate, and project mixed effects models fitted with the Vector Auto-regressive Spatio-Temporal Modeling approach. Given transition from VAST to sdmTMB, mostly deprecated, though still has some useful pieces. 

## Ecological Forecasting
### Overview
Global climate change is reshaping marine ecosystems, introducing growing uncertainty for the people and communities that depend on them. In rapidly warming regions like the Northeast U.S. Large Marine Ecosystem (NES LME), physical and biological changes are already influencing the growth, survival, and productivity of many ecologically and economically important species. These shifts present complex challenges for marine management, where decisions must increasingly account for dynamic and uncertain futures rather than relying solely on historical baselines.

Ecological forecasting is an emerging field that aims to provide forward-looking information about ecosystem states on timescales relevant to decision-making — from seasons to decades. To meet this need, we develop and refine near-term forecasts by integrating species distribution models, spatio-temporal statistics, and emerging artificial intelligence tools. By linking these models to real-world decision contexts, we aim to deliver actionable forecasts that support resource users, managers, coastal communities, and policymakers. Alongside these applications, our work also contributes to model development and ecological theory. We are particularly focused on understanding and improving predictive skill in distribution models, and on capturing ecological responses that vary across space and time — from basin-wide environmental shifts to local-scale fisheries impacts. In doing so, we help create the space to anticipate change, evaluate trade-offs, and make more informed decisions in an increasingly uncertain ocean.

### Current Projects
- CINAR Near-Term Ecological Forecasting Workshop
- [NASA Fisheries and Climate Toolkit](https://www.gmri.org/projects/using-satellite-data-support-sustainable-fisheries/) 

### Relevant Publications
- Grüss and Allyn et al. *In review.* Probabilistic forecasts of fish abundances with spatio-temporal models to support fisheries management. 
- Farchadi et al. 2025. Data Integration Improves Species Distribution Forecasts Under Novel Ocean Conditions. *Ecography.*
- Allyn et al. 2025. Contrasting Species Distribution Model Predictability Under Novel Temperature Conditions. [*Diversity and Distributions.*](https://doi.org/10.1111/ddi.70036)
- Lewis et al. 2023. The power of forecasts to advance ecological theory. [*Methods in Ecology and Evolution.*](https://doi.org/10.1111/2041-210X.13955)

## Predator-Prey Dynamics
### Overview
Understanding ecosystem change requires moving beyond single-species perspectives to capture the interactions that structure marine food webs. Predator–prey dynamics play a central role in shaping species distributions, energy transfer, and ecosystem resilience. By studying how species co-occur and respond to shared environmental drivers, we gain deeper insight into the conditions that support foraging hotspots, productivity, and trophic connectivity in a changing ocean.

Our work in this area advances from traditional single-species distribution models to joint species distribution models that incorporate inter-species associations and shared habitat use. These approaches offer a more holistic view of community dynamics and allow us to identify spatial patterns of energy flow through the ecosystem. Increasingly, we are also incorporating marine birds into this work, both as top predators in their own right and as sentinels of broader ecosystem change. Their movements and distributions can reveal biologically important areas where prey are aggregated and energy is transferred through the food web. By integrating spatial ecology, predator–prey modeling, and ecosystem indicators, we aim to build a more complete picture of marine ecosystem function, which can inform ecosystem-based management and identify ecologically significant areas under pressure from climate and human use.

### Current Projects
- [NSF Nutrional Ecology of Climate Change](https://gmri.org/projects/nutritional-ecology-climate-change/)
- [National SeaGrant American Lobster Research Program: Improving lobster distribution models](https://gmri.org/projects/improving-lobster-distribution-models/) 
- [NSF Research Experience for Undergrads: Casco Bay Marine Bird Monitoring Pilot Study](https://gmri.org/projects/casco-bay-aquatic-systems-survey-cbass/)

### Relevant Publications
- Allyn et al. *In prep.* Intra-annual variation in species distributions within a rapidly warming marine ecosystem.
- Hermann et al. *In prep.* Diet breadth and quality is declining for many fish predators in the warming Northeast US Continental Shelf. 
- Allyn et al. 2015. Assessing a paired logistic regression model of presence-only data to map important habitat areas of the rare Kittlitz's Murrelet *Brachyramphus brevirostris*. [*Marine Ornithology.*](http://www.marineornithology.org/PDF/43_1/43_1_65-76.pdf)
- McKnight and Allyn et al. 2013. ‘Stepping stone’pattern in Pacific Arctic tern migration reveals the importance of upwelling areas. [*Marine Ecology Progress Series.*](https://www.int-res.com/articles/meps_oa/m491p253.pdf)

## Marine Spatial Planning and Resource Management 
### Overview
As marine ecosystems change and ocean uses diversify, there is a growing need for science that can inform balanced, forward-looking decisions about how we manage space and resources. From offshore energy development to habitat conservation and sustainable fisheries, marine spatial planning requires clear, spatially explicit information about where species are likely to be — and how those patterns may shift over time.

Our work brings species distribution models into these applied decision contexts. By integrating our ecological predictions with human-use data, we support planning efforts that seek to reduce conflicts among competing uses, improve spatial efficiency, and protect ecologically important areas. In fisheries management, these tools help anticipate shifts in stock availability, identify potential changes in overlap between target species and fleet activity, and inform adaptive strategies under climate change. By aligning ecological modeling with the scales and priorities of resource governance, we aim to provide actionable science that supports more equitable, effective, and resilient ocean management.

### Current Projects
-  Mid-Atlantic Fisheries Management Council Contract: Evaluating indicators and developing a framework to support 
fisheries governance of shifting stocks.
- [GMRI Climate Fisheries Resource Hub](https://gmri.org/projects/climate-adaptation-fisheries-resource-hub/)
 
### Relevant Publications
- Farchadi et al. 2024. Marine heatwaves redistribute pelagic fishing fleets. [*Fish and Fisheries.*](https://onlinelibrary.wiley.com/doi/full/10.1111/faf.12828#:~:text=https%3A//doi.org/10.1111/faf.12828)
- GMRI. 2024. The Gulf of Maine Research Institute Climate Adaptation Resource Hub for Fishing Communities. [Online.](https://gmri.org/projects/climate-adaptation-fisheries-resource-hub/)

